README.md

Instruct users to clone the repo in case that wasn't clear

Add more granular instructions

---

calculator/calculator.js

While the previous return functioned the same (because it was calling another factorial function), it was not recursive. All credit still to ThirtyThreeB, just thought this might confuse some people and was worth fixing!

Fix return value of recursiveFactorial function

---

leapYears/README.md

Everybody in the Southern hemisphere experiences winter in July and that's normal, so the original remark added an unnecessary (and off-topic) layer of confusion.

Further clarify guidelines

---

leapYears/README.md

I got confused after seeing the code in solution that definition and solution didn't match so this is what I found on Wikipedia "(except for years evenly divisible by 100, which are not leap years unless evenly divisible by 400)" but earlier it was written here "except for years which are both divisible by 100 and not divisible by 400." 
I maybe wrong here, not knowing that these two statements maybe are indicating two different things, if that's the case, then feel free to not apply the changes and do let me know. 😄 
P.S. - I corrected "effects" to "affects" too.

Update Leap Year Definition and grammar

---

helloWorld/helloWorld.spec.js

Quick fix to bring the actual spec file in line with the example in the README.

helloWorld.spec.js: Fix disparity between the README example and spec file

---

13_caesar/README.md

Fixed a typo where the semicolon should've been a single quote.

Fixed typo in caesar cipher excersize

---

01_helloWorld/README.md

change `'says hello world'`  to   `'says "Hello, World!" '` to be identical to the code in the (helloWorld.spec.js) file.

fix 'says hello world' in README.md

---

README.md

This PR is the third task of [#23248](https://github.com/TheOdinProject/curriculum/issues/23248)
The new Node.js installation instructions have been merged into the main TOP site and are now located [here](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/installing-node-js).
This PR updates the README to reflect the change.

Update NPM instruction to new lesson link

---

09_palindromes/palindromes.spec.js

As all palindromes have the exact same first and last letter, people only had to test for first and last letter equallity, and the only test where it should return false, it has the first and last letters being different. to pass the whole test people only had to test for first and last letter weither they are equal or not, which make mistakes like this pass the test : 
```js
const palindromes = function (input) {
let str = input.replace(/[^0-9a-z]/gi, "").toLowerCase();
for (var i in str) {
if (str[i] != str[str.length-1-i]) {
return false;
}
return true;
}
};
```
this mistake happens to a lot of people, where they return true inside rather than outside the loop. I myself did this mistake many times.
My change will make sure that the first and last letter of a none-palindrome sentence …

Fix palindromes false positive test

---

README.md

This change is in relation to [this PR](https://github.com/TheOdinProject/curriculum/pull/23588). Both PRs aim to improve the organization and clarity of the Foundations>JavaScript Basics>Fundamentals Part 4 lesson.
The overarching goal is to dramatically reduce the number of learners that skip the necessary set-up steps for the TDD exercises.

Remove irrelevant text from README about order of completion

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

I have created PR and Issue templates to be inline with our other repos, specifically our main TOP repo (with variations to better fit the purposes of this repo).

Templates: Create PR and Issue files

---

07_tempConversion/README.md
07_tempConversion/tempConversion.js
07_tempConversion/tempConversion.spec.js

The current function names in tempConversion are unreadable and directly contradict eveything stated about writing clean code two lesson earlier this PR updates them to be more inline 
* Changes the function names to be more in line with the convention recommended in the clean code lesson
* Updates README.md and tempConversion.spec.js to account for these changes
* #300
Discussed in https://discord.com/channels/505093832157691914/1041022385123491840. While there was some valid reasoning that the convention we lay forth in the clean code isn't always used nor always the standard convention, I saw no real opposition to the specific issue of updating these names.
-   [x] I have thoroughly read and understand [The Odin Project Contributing …

07_tempConversion: Update tempConversion function's naming

---

08_calculator/solution/calculator-solution.js

See separate PR "Removed array syntax in multiply test #359"  
https://github.com/TheOdinProject/javascript-exercises/pull/359
Updated the solution for the `multiply` function with one that does not take arrays as input. 
There may be more elegant ways to write this function, but it passes the test as long as the [brackets] are removed. 
Closes #XXXXX
-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `01_helloWorld: Update test cases`
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in …

New solution to match updated test syntax

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
README.md

We are centralizing to https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md as the single source of truth for CONTRIBUTING.md
Changes all https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md links to https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md
Part of https://github.com/TheOdinProject/theodinproject/issues/3901
-   [x] The `This PR` section has a bullet point list …

CONTRIBUTING.md: repoint contributing links to .github/CONTRIBUTING.md

---

.github/PULL_REQUEST_TEMPLATE.md

- We've moved from a `solutions` branch to `/solution` folders
- Updates the Pull Request template to reflect this change

Fix: change requirement to reflect solutions change

---

08_calculator/calculator.spec.js
08_calculator/solution/calculator-solution.js
08_calculator/solution/calculator-solution.spec.js

Reformat test parameters allow for more consistency
Modified the test for the sum function in calculator.spec.js, as well as the sum and multiply functions in calculator-solution.spec.js file to expect rest parameters instead of expecting an array parameter. Modified the sum function in calculator-solution.js to work with the new test for the sum function. There was no need to modify the multiply function in calculator-solution.js as it already expects rest parameters

Reformat test parameters for consistency

---

12_findTheOldest/findTheOldest.spec.js

The tests for 12_findTheOldest lead to frequent confusion because of the disconnect between the English sentence in the test description, and the expected outcome of the test. 
The confusion comes from expectations of how we use English. Culturally in English speaking countries (i can't speak for others), we are not used to referring to anyone who is already dead as the oldest. When 2 people are dead, and someone is alive and 17 years old, that person is generally thought about as "the oldest", because oldest is reserved for the living. 
Culturally, the second test: *'finds the person with the greatest age if someone is still living'* would be considered ambiguous English. That's the test that causes the most confusion.
Additionally, the test passing arguments are too similar to the …

12_findTheOldest: Clarify test descriptions

---

05_sumAll/solution/sumAll-solution.js

I believe this way of swapping the values between variables in JavaScript is better for learners to know about since it is more common and reinforces understanding on array destructuring
Change the swapping algorithm to the standard way of swapping in JavaScript using array restructuring. Edit: Change for loop condition as well to the standard way
-   [x] If this PR includes changes that needs to be updated on the …

Update sumAll-solution.js swap algorithm to standard method

---

README.md

People are very commonly concerned when they see their exercise solutions differ from the provided solutions. This is primarily from two parts:
- Learners are initially directed straight to the relevant exercise directory and not told to read the repo README (where a note about the provided solution is). *This has been addressed in [#27055](https://github.com/TheOdinProject/curriculum/pull/27055)*
- The README note on provided solutions, despite saying the provided one isn't the only solution, the rest of the sentence seems to be interpret-able as "if your solution differs, check with the community if it's actually allowed".
- Improves the wording of the relevant README note to clarify intent (unified wording with `css-exercises` repo)
Closes …

Repo README: Improve wording regarding TOP provided solution

---

12_findTheOldest/findTheOldest.spec.js

fix ambiguity in test description , old was 'finds the person with the greatest age if someone is still living.'
remove redundant test that checks for 'finds the person with the greatest age if the OLDEST is still living' since both this and the above test for ability to check if there is no death year field.
I had faced difficulty understanding the tests so wanted to make it easier for others to understand the test when they are learning
- Remove one of the three tests as I think it is redundant
- Modify the test description of the last test to make it more concise
Closes #XXXXX
-   [x] The title of this PR follows the `location of …

12_findTheOldest fix ambiguity and remove redundant test description

---

09_palindromes/solution/palindromes-solution.js

#319 replaced the regex solution for the palindromes exercise with a non-regex solution, which definitely was the right move given the context of the curriculum at that point as well as regular gripes in the community from learners who get hit in the face with a regex brick wall upon seeing the solution. However, this was only reflected in the `solutions` branch and not in the `main` branch.
Since then, changes to the `main` branch's solutions test file have not been reflected in the `solutions` branch and it seems this branch is no longer in use/being updated; learners are also unlikely to be aware of this branch and will just use the solutions directory from the `main` branch.
- Replaces the `main` branch `09_palindromes` regex-based solution with the non-regex solution from the …

09_palindromes: Replace regex solution with non-regex version

---

09_palindromes/solution/palindromes-solution.js

One of the variables uses `let` as a carryover from the original solution adapted from.
This variable is never reassigned, so would be better declared with `const`.
A tiny pedantic change but since the rest of the function's non-reassigned variables are declared with `const`, this keeps things consistent and prevents any "why use let here and const there?" confusions from learners.
- Changes a non-reassigned variable to be declared via `const` instead of `let` 
N/A
-   [x] The `Because` section …

09_palindromes: Use const for solution variable

---

12_findTheOldest/README.md
12_findTheOldest/solution/findTheOldest-solution.js

I felt like the solution is a little too verbose. I also wanted to take this moment to appreciate the `??=` operator, I think learners will find it interesting at least :>

Exercise 12: Make solution less verbose

---

04_removeFromArray/removeFromArray.js
04_removeFromArray/removeFromArray.spec.js
05_sumAll/README.md

The test cases for the sumAll question suggested that the integers needed to be positive however no such thing was mentioned in question statement .
Changes the question statement which previously stated to 'form a function for integers' to 'form a function for positive integers'
Closes #255 
-   [x] If this PR addresses an open issue, it is linked in …

05_sumAll: Update README.md

---

06_leapYears/solution/leapYears-solution.js

… of this exercise.
This PR changes the solution for Exercise 06 - leapYears, to align the solution with what has been taught up until this point of the course.
- Changes solution.js to use if statements in combination with the && operator in order to match the hint in README.md and to better align with the concepts taught up to this point in the course.
Closes #482 
-   [x] The `This PR` section has a bullet point list describing the …

06_leapYears/solution: Fix solution.js to align with README.md hint

---

02_repeatString/README.md
02_repeatString/solution/repeatString-solution.js

There is a builtin method for accomplishing the same outcome, so I have updated the instructions as the point of the exercise is to practice loops.

feat(repeatString): add instruction to use loops for implementation rather than builtin method

---

06_leapYears/README.md

The present problem statement, borrowed from Chris Pine, does not clearly state the leap year calculation rules, which is indeed confusing. 
- I updated the README with an external link outlining the nested rules for leap years. 
Closes #XXXXX
Link to the added break-up of the leap years explanation:
https://time-and-calendar.com/leap-years/#:~:text=How%20to%20Know%20if%20Certain%20Year%20is%20a%20Leap%20Year
-   [x] The `This PR` section …

Update 06_leapYears README.md with a reference

---

02_repeatString/repeatString.spec.js

The original code had "hey" as the seed string value and hence the comment on line-29 mentions "hey". But the last commit on the code changed "hey" to "odin".
We can either change instances of comment or the code. I propose changing the code instance from "odin" to "hey" for consistency.
There is an inconsistency between the comment on line-29 and its corresponding code on line-32. It provides clarity to the learner by maintaining the same example of "hey" instead of "odin".
- Replaced two instances of "odin" with "hey" on line-32
Closes #XXXXX
-   [x] The title of this PR follows the `location of change: brief description of change` …

02_repeatString - Line-32, replace "odin" with "hey"

---

02_repeatString/solution/repeatString-solution.spec.js

As asked by @JoshDevHub in a discussion of a related PR, I made a similar change to this solution. 
More on: https://github.com/TheOdinProject/javascript-exercises/pull/505#pullrequestreview-2588692590
In the earlier code, the comment description mentioned "hey" as a sample string but the code had "odin" string. This update addresses that tiny gap between sample comments and related code.
- replaced "odin" with "hey" on line-32
Closes #XXXXX
How it started: https://github.com/TheOdinProject/javascript-exercises/pull/505#pullrequestreview-2588692590
-   [x] The title of this PR follows the `location of change: brief description of change` …

02_repeatString/solution - Line-32, replace "odin" with "hey"

---

02_repeatString/repeatString.spec.js
02_repeatString/solution/repeatString-solution.spec.js

The instructions for 02_repeatString make it clear that the exercise is for practising loops, so the user must not use the built-in `String.prototype.repeat` method to complete this, even if it leads to the same result. Despite this, the test suite doesn't actually prevent its usage. It would be worth adding a single test that fails upon its use and explains why, in order to encourage practising loops.
- Adds test preventing use of `String.prototype.repeat` in both main and solution test files
N/A
- …

02_repeatString: Add test preventing use of `String.prototype.repeat`

---

CONTRIBUTING.md
README.md

Most of our other repos have their own specific `CONTRIBUTING.md` that extends the general contributing guide.
A surprisingly not-that-uncommon thing I've seen in the community is learners starting these exercises for the first time, following the installation instructions, but then also doing the "Adding New Exercises" instructions at the bottom of the README, even if they're not actually adding any new exercises.
It would make sense to extract that section to a separate contributing guide for this repo, which will keep the README focused on the instructions for installing things and using the exercises, eliminating any accidental `npm run generate`s and all the joy that comes with ensuing confusion.
- Writes repo-specific contributing guide.
- Removes "Adding New Exercises" instructions …

Add repo-specific CONTRIBUTING.md

---

05_sumAll/solution/sumAll-solution.spec.js
05_sumAll/sumAll.spec.js

Improving the tests in javascript-exercises 05 to ensure solutions match expected behavior. Current tests don't require adding numbers between a provided interval, just all the numbers up to the biggest value. This allows incorrect solutions (that don't consider the lower bound if it isn't 1) to pass the tests.
- Modifies a test case to use a range with a lower bound other than 1.
Closes [#510](https://github.com/TheOdinProject/javascript-exercises/issues/510) 
-   [x] The `Because` section summarizes …

05_sumAll: Fix tests to require correct range summation

---

07_reverseString/README.md

Odin Project. In order to get this pull request (PR) merged in a reasonable amount of time, you must complete this entire template. -->
Removing this was missed in #509 presumably because it wasn't expected for this exercise to repeat the "skipped tests" info.
- Removes redundant "skipped tests" paragraph from exercise 7's instructions.
Closes #542
- …

Remove duplicate "skipped test" instruction

---

06_repeatString/repeatString.spec.js

The test description in `repeatString.spec.js` had a grammatical typo — it said "1 times" instead of the correct singular "1 time". This can cause confusion and reduces clarity in the tests.
- Fixes the typo in the test description on line 10 of `repeatString.spec.js`.
- Changes the string from `'repeats the string 1 times'` to `'repeats the string 1 time'`.
Closes #546
This is my first open source contribution, happy to learn and improve!
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `06_repeatString: Fix test description typo`
-   [x] The `Because` section summarizes the reason …

Fix typo: change '1 times' to '1 time' in repeatString test
