TheOdinProject/javascript-exercises

calculator/calculator.spec.js
The zero factorial is equal to 1.
[Factorial - Wikipedia](https://en.wikipedia.org/wiki/Factorial#Definition)
=> zero factorial is 1

README.md
if a user does not have node he does not have NPM, but a user could have node without NPM
=> Changes node version to NPM

calculator/calculator.spec.js
Add xit to problems on calculator.spec.js file to make it consistent with other spec files of the javascript exercise library.
=> add xit to problems for consistency

leapYears/README.md
Myself and others struggled with the description of a leap year as provided here. This quote explains it clearly and succinctly. It's from Chris Pine's Learn to Program, so the source is cited.
=> Clarify leap year rules

calculator/calculator.js
The reduce() method syntax for callbacks assigns the accumulator value followed by the currentValue, so I think the above variables should be switched.
=> Reduce Method Solution

fibonacci/fibonacci.spec.js
I believe some students may be familiar with the recursive definition of the Fibonacci sequence.  Instead of using the iterative version, they may come up with a solution like this for a start:
```javascript
const fibonacci = function(n) {
if (n === 1 || n === 2) {
return 1;
} else {
return fibonacci(n - 1) + fibonacci(n - 2);
}
}
```
This solution will fail the test case where the input is a negative number, but with the given test case for string (`fibonacci("8")`), it will pass. They may mistakenly think that their solution suffices to cover for all string cases.
However, the only time will this function fails for the string counterpart is when we attempt `fibonacci("1")` or `fibonacci("2")`. This will cause a `RangeError: Maximum call stack size exceeded` due to the fact that at the …
=> Add more tests for fibonacci

removeFromArray/README.md
Rest parameters are already arrays unlike 'arguments' and they can be used in arrow expressions. Just find it a bit simpler
=> Added ...rest parameters as a link to deal with optional parameters

helloWorld/README.md
Just fixed a code indentation glitch on the readme for helloWorld
=> Fix code indentation on helloWorld README.md

removeFromArray/README.md
Updates removeFromArray/README.md to match function names across files, for the following reason:
- function name in exercise readme is `remove(...)`
- function name in exercise and test file is `removeFromArray(...)`
=> updates function name to match exercise file

sumAll/sumAll.js
it flows better logically to first check if the inputs are a number than to check if they are negative.
=> changed the order of if conditions

palindromes/palindromes.spec.js
The second test would originally test if it works with upper-case letters and punctuation. but the description of the test is "works with punctuation". I think it is better to either put both in the description or make a new test that solely tests each different thing.
=> added a test and changed an old one

caesar/README.md
Helped someone with this yesterday, They did it all without unicode/charCodeAt()/charCode(). I'm pretty sure the only reason I knew to use that was because I had peaked at the solutions. 
Just an idea!
=> Added hint to README.md Instructions

reverseString/README.md
Because `repeatString/` is Exercise 02
and `removeFromArray/` is Exercise 04
=> Correct exercise number

02_repeatString/README.md
Edit repeatString README to add a paragraph about including arguments, as well as to merge two bullet points into one.
=> Edit repeatstring readme

calculator/calculator.js
Added a small alternative solution to one of the problems in the calculator project.
=> added alternate solution to multiply using Exponentiation operator

findTheOldest/findTheOldest.js, getTheTitles/getTheTitles.js, helloWorld/helloWorld.js, leapYears/leapYears.js, repeatString/repeatString.js, reverseString/reverseString.js, tempConversion/tempConversion.js
I found some missing semicolons and decided to fix them
=> Fixed semicolons

01_helloWorld/README.md
Corrected the word "this" so it starts with an upper case "T".
=> Fixed a typo in line 41

03_reverseString/reverseString.js
Making it consistent with other exercise setups
=> Remove predefined parameter from reverseString.js

palindromes/palindromes.js
Hi,
While both the original code and the new code do the same thing, I feel like the new one reads better especially for beginners just getting a hang of RegExp in Javascript.
=> Improve the readability of the RegExp

palindromes/palindromes.js
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01_helloWorld: Update test cases
-   [x] I have ensured any exercise files included in this PR have passed all of their tests
<hr>
Fixes a missing variable declaration.
=> palindromes: Add mising variable declaration

tempConversion/README.md, tempConversion/tempConversion.js, tempConversion/tempConversion.spec.js
Companion pull request to #299 
* Updates the solutions branch to account for changes made in the main branch
Related to and must be merged together with #299 
See #299 
-   [x] If this PR includes changes that needs to be updated on the `solutions` branch, I have …
=> tempConversion: Update function names to account for changes in the base branch

sumAll/sumAll.spec.js
Updates solution branch to match #242
=> 05_sumAll: Add new test - update solutions

removeFromArray/removeFromArray.js
This spares us from having to extract `array` from `args` and is more idiomatic (I think).
Complete the following REQUIRED checkboxes:
Complete the following checkboxes ONLY IF they are applicable to your PR. You can complete them later if they are not currently applicable:
-   [x] I have ensured any exercise files included in this PR have passed all of their tests
<hr>
**1. Because:**
- A concise, idiomatic way to handle `array` would be to declare it as an independent parameter rather than …
=> JS exercises solutions - removeFromArray: Make `array` an independent parameter

caesar/caesar.js
The given solution is a bit messy and harder to understand than it needs to be.
Improves the readability of the solution. Follows the rules given in the [Clean Code](https://www.theodinproject.com/lessons/foundations-clean-code#rules-of-thumb) lesson and adds some additional clarifications.
Not related to any Issue.
- Motivated by the discussion in this [Discord thread](https://discord.com/channels/505093832157691914/1041022385123491840). 
- I kept the initial function name for `caesar` even though it does not include a verb, because I can't think of anything more succinct. `encipher` might be an option, but that loses the reference to the name of the cipher.
- There are still many [Magic Numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)) in the source code, but I think …
=> Caesar: clean up solution

palindromes/palindromes.js
Since the readme didn't suggest regex, I got the impression we were to do this wihtout regex. But after finishing, and checking the solution, there was only a regex version.
- Regex Method commented
-Non Regex method with comments attached.
Closes #XXXXX
-   [x ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] If …
=> 09 Palindromes: Non Regex Solution Added

09_palindromes/palindromes.spec.js
Proposed by @thatblindgeye.
Strings with numbers inside of them can also be palindromes. This last test checks such strings.
- The file _palindromes.spec.js_ now includes a 7th test.
Closes #237 (I think. I might be wrong though)
-   [ ] If this PR includes changes …
=> 09_palindromes: Add test for strings with numbers

09_palindromes/palindromes.spec.js, 09_palindromes/solution/palindromes-solution.spec.js
The solution test file for palindromes needed a new test added in.
- Updates the solution file
- Adds `.skip` to the non-solution test file
Closes #XXXXX
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If this PR includes changes that needs to be updated on the `solutions` branch, I have created another PR …
=> 09_palindromes: update solution test file

09_palindromes/palindromes.spec.js, 09_palindromes/solution/palindromes-solution.js, 09_palindromes/solution/palindromes-solution.spec.js, 10_fibonacci/solution/fibonacci-solution.js, 10_fibonacci/solution/fibonacci-solution.spec.js
The 09_palindromes and 10_fibonacci exercise solutions weren't meeting all their goals (as evidenced by the issues raised about them).
For palindromes, the old solution removed numbers entirely, whereas this one treats them like letters and checks if they are evenly spaced. More importantly, the old solution test seemed to check if the numbers were palindromic, but because the solution replaced them with "", it wasn't testing what it seemed to. I added a new test to differentiate between the palindromic "rac3e3car" and the non-palindromic "r3ace3car".
For fibonacci, the old solution didn't use arrays, and since nearly all the exercises leading up to it iterated on arrays, it seemed better to have that be the solution here. Also, my solution accounts for entering 0 as an argument without …
=> 09_palindrome and 10_fibonacci: Update solutions

03_reverseString/README.md
Just like it was mentioned in the previous exercise to remove the .skip from test.skip() in the spec.js file.
It would remind the people that there are other skipped test cases too that the program needs to pass and how to unskip those might help some people who left the assignments after completing the `02_repeatString` and are coming back on `03_reverseString` after quite some time. 
- Changed readme,md to add how to unskip the test cases.
Closes #XXXXX
-   [x] The `Because` section summarizes …
=> `03_reverString: Updated README.md to add unskipping the skipped test cases`

12_findTheOldest/README.md
Added clarification to instruct learner to look in test case to understand object structure
Learners could benefit from being guided to test file to understand the object structure that will be passed to the function he/she will have to write. Learners are used to readme files of all pervious exercises (except "ex08 - Calculator"), providing them with enough details on the inputs / outputs to get started. Exercise 12 is an exception and throws a learner off from what they're expecting.
- Updates exercise 12's readMe with a reminder to look at the test file to understand the argument structure that a learner should write the solution based on.
-->
Related to #375
-   [x] I have thoroughly read and understand [The Odin Project Contributing …
=> Ex12 readme clarified

10_fibonacci/README.md
It fixes the Fibonacci series example given in README.md for 10_fibonacci
- Change made to README.md file in 10_fibonacci. Changed provided example to 0, 1, 1, 2, 3, 5, 8, etc.
- Added semicolons to the function calls in README.md
Closes #381
-   [x] If this PR includes any …
=> 10_fibonacci: Update README.md

README.md, package-lock.json, package.json
When running `npm install` the current versions produce numerous warnings about vulnerabilities and deprecated packages. This often confuses new learners.
- Update package.json with latest versions of the modules.
- Add a note to the top level README that these warnings can be safely ignored.
Closes #250 
After updating I ran the tests in each solution folder to verify that the all run and pass.
-   [x] The `This PR` section has a bullet …
=> Javascript exercises - Update package.json and package-lock to latest module versions

10_fibonacci/solution/fibonacci-solution.js
Students get to learn an alternative way to solve the fibonacci problem using an array with 2 values, especially for the ones who are currently in fundamentals part 5 learning about arrays.
- Add fib array containing the value 0 and 1.
- Abbreviate fibonacci calculation in for loop.
- return fibonacci count.
Closes #XXXXX
-   [x] If this PR addresses an …
=> 10_fibonacci: Add alternative solution in fibonacci-solution.js

02_repeatString/solution/repeatString-solution.spec.js
- Should be 'randomly' instead of 'randomaly' on line 31
Closes #XXXXX
-   [x] If this PR includes any changes that affect the solution of an exercise, I've also updated the solution in the `/solutions` folder
=> 02_repeatString/solution/repeatString-solution.spec.js: Fix typo

02_repeatString/repeatString.spec.js, 02_repeatString/solution/repeatString-solution.spec.js
This corrects a typo in the repeatString test case.
- Updated line 32 from `(...).match(/((hey))/g).length).(...)`
- Updated to `(...).match(/(hey)/g).length).(...)`
Closes https://github.com/TheOdinProject/javascript-exercises/issues/240
N/A
-   [x] If this PR includes any …
=> corrected typo in the test case for 02_repeatString

07_tempConversion/README.md
This provides clarity around the assignment. I updated from `module.exports of spec.js file` to `module.exports of main javascript file`.
- Provided clarity around the assignment
- Old - `module.exports of spec.js file`
- Updated - `module.exports of main javascript file`
Closes #388
-   [x] If this PR addresses an open issue, it is linked in the …
=> 07_tempConversion updated the readme file for clarity on the assignment

04_removeFromArray/solution/removeFromArray-solution.js
It's best to encourage learners to use `const` rather than `var`
=> Exercise 4: Use const instead of var

08_calculator/solution/calculator-solution.js
Learners would not have been taught about Recursion by this point.
A solution like this could send them down an unnecessary rabbit hole when it will be covered later on in the course.
=> Exercise 8: Remove recursive solution

README.md
The notes for avoiding solution PRs to the repo and ignoring NPM ERR statements could be better differentiated from the other setup instructions.
- Place PR note in an Important note box
- Place NPM ERR statement note in a note box
Closes #XXXXX
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If this PR includes …
=> Change styling of notes for avoiding PRs and error messages

05_sumAll/README.md
The problem statement says:
"Implement a function that takes 2 positive integers and returns the sum of every number between (and including) them"
It should say:
"Implement a function that takes 2 positive integers and returns the sum of every integer between (and including) them"
In the sumAll folder the statement problem from number to integer is fixed
Closes #476
-   [x] The `This PR` section has a bullet point list describing the …
=> Changed number to integer in sumAll

.npmrc, package-lock.json, package.json
This change will prevent any old node or npm version from installing any packages. With this, npm will throw an error and exit immediately. This is to prevent the accidental use of unsupported versions which might cause some issues that are hard to pin-point.
A person on Discord was getting some syntax errors when running Jest after installing the packages. It took us a while to figure out that the person was using a really old version of node. The additions in this PR will prevent something like this from happening. If someone tries to run the `npm install` command with an outdated node/npm version inside the repo, then npm will exit with an error, informing the user their version is too low and what the minimum required version is.
- Adds an engines field in the `package.json` file with …
=> Project Root: Add minimum npm & node version requirements

08_calculator/calculator.spec.js, 08_calculator/solution/calculator-solution.spec.js
There was only one test case for each of subtract and power, allowing for test fitting to pass all tests
- Adds more cases to subtract
- Adds more cases to power
Closes #493
-   [x] If this PR includes any changes that affect the solution of an exercise, I've also updated …
=> 08 Calculator: Add more test cases for subtract and power

08_calculator/solution/calculator-solution.js
The solution includes a guard clause that does not change the functionality of the function. The variable "product" is declared with a value of 1, so in the case of 'n === 0' the for loop won't run (let i = n; i > 0), and it will return product with the declared value of 1
* removed a redundant line
https://discord.com/channels/505093832157691914/690590001486102589/1296871107109982208 
-   [x] The `This PR` section has a bullet point list …
=> 08_calculator: Remove redundant solution code

04_removeFromArray/README.md
Improves readability
- Adds missing whitespace
- Replaces 'javascript' with 'JavaScript'
=> Whitespace and capitalization correction

README.md
This PR corrects a simple typo mistake in README file. 
- Change 'supress' to 'suppress'
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If this PR includes any changes that affect the solution of an exercise, I've also updated the solution in the `/solutions` folder
=> README: Correct typo

12_calculator/solution/calculator-solution.js
when learning about JavaScript operators, we are introduced to different operators (here: https://javascript.info/operators). Therefore, the solution (to get the power) for the calculator exercise should just stick to using the exponentiation operator (`**`) instead of a method that seems to come out of nowhere.
* Replaces the solution for `12_calculator` (where you get the power) with `a**b` (instead of `Math.pow(a, b)`)
-   [x] The `This …
=> 12_calculator: Use operator instead of method in the solution

06_repeatString/README.md, 09_sumAll/README.md
The original hints for [06_repeatString][1] and [09_sumAll][2] exercises were overly prescriptive and essentially outlined the algorithm, which reduced the opportunity for learners to think critically about the problem and design their own solution.  
- Rewords the hints for [06_repeatString][1] and [09_sumAll][2] exercises to make them less explicit.  
- Focuses on encouraging learners to reason through the problem, rather than following step-by-step instructions.  
Closes #461 
N/A 
-   [x] The …
=> Exercise README: Make hints less explicit to encourage problem-solving

07_reverseString/README.md, 07_reverseString/solution/reverseString-solution.js
Previous hint was little more prescriptive so we made the hint general so people going through excercise don't have to think in constraining way as previous hint would have made them to think.
- Changed the hint to new one.
- And different approach  commented out solution in solution file.
Closes #575 
-   [x ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [ x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01_helloWorld: Update test cases`
-   [ x] The `Because` section summarizes the reason for this PR
-   [x ] The `This PR` section has a bullet point list describing the changes in this PR
-   [x ] If this PR addresses an open issue, it …
=> Added hint and a commented out solution in  Javascript excercises:  07 string reverse 

README.md
Makes clearer that the provided solutions are only examples, not an ideal that's expected or intended as a "comparison for marking".
- Rephrases wording around provided solution in the repo README
Closes #XXXXX
-   [x] If this PR includes any changes that affect the solution …
=> Clarify language in repo README about solutions
